name = "the-third-voice-mvp"
compatibility_date = "2024-09-13"

[build]
command = "cd frontend && npm run build"
cwd = "."

[build.environment_variables]
NODE_VERSION = "18"

[[pages_build_output_dir]]
value = "frontend/.next"