# .github/workflows/health-monitor.yml
name: Health Check Monitor

on:
  schedule:
    # Check every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch: # Manual trigger

jobs:
  health-monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check Pi Server Health
      id: health-check
      run: |
        echo "Checking Pi server health..."
        
        if curl -f -s --max-time 15 https://api.thethirdvoice.ai/health > /dev/null 2>&1; then
          echo "status=healthy" >> $GITHUB_OUTPUT
          echo "Pi server is responding normally"
        else
          echo "status=down" >> $GITHUB_OUTPUT
          echo "Pi server is down or unreachable"
        fi
        
        # Also check backup server
        if curl -f -s --max-time 10 https://the-third-voice-mvp.onrender.com/health > /dev/null 2>&1; then
          echo "backup-status=healthy" >> $GITHUB_OUTPUT
          echo "Render backup server is healthy"
        else
          echo "backup-status=down" >> $GITHUB_OUTPUT
          echo "Render backup server is also down!"
        fi
    
    - name: Send Discord Notification (Pi Down)
      if: steps.health-check.outputs.status == 'down'
      run: |
        BACKUP_STATUS="${{ steps.health-check.outputs.backup-status }}"
        
        if [ "$BACKUP_STATUS" == "healthy" ]; then
          MESSAGE="🟡 **Pi Server Down** - Backup server is healthy
          
          **Status:** Primary server unreachable
          **Backup:** Render server operational  
          **Action:** Consider switching to backup manually
          **Time:** $(date -u)
          
          Pi Server: https://api.thethirdvoice.ai/health ❌
          Backup: https://the-third-voice-mvp.onrender.com/health ✅"
        else
          MESSAGE="🔴 **CRITICAL: Both Servers Down**
          
          **Status:** Both primary and backup unreachable
          **Action:** Immediate attention required
          **Time:** $(date -u)
          
          Pi Server: https://api.thethirdvoice.ai/health ❌  
          Backup: https://the-third-voice-mvp.onrender.com/health ❌"
        fi
        
        # Send to Discord (if webhook configured)
        if [ -n "${{ secrets.DISCORD_WEBHOOK }}" ]; then
          curl -H "Content-Type: application/json" \
            -d "{\"content\":\"$MESSAGE\"}" \
            "${{ secrets.DISCORD_WEBHOOK }}"
        fi
    
    - name: Send Email Notification (Pi Down)  
      if: steps.health-check.outputs.status == 'down'
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "🚨 Third Voice API - Pi Server Down"
        body: |
          Pi Server Health Check Failed
          
          Status: Primary server unreachable
          Backup Status: ${{ steps.health-check.outputs.backup-status }}
          Time: $(date -u)
          
          Pi Server: https://api.thethirdvoice.ai/health
          Backup: https://the-third-voice-mvp.onrender.com/health
          
          ${{ steps.health-check.outputs.backup-status == 'healthy' && 'Backup server is operational. Consider switching manually.' || 'CRITICAL: Both servers are down!' }}
        to: ${{ secrets.NOTIFICATION_EMAIL }}
        from: ${{ secrets.EMAIL_USERNAME }}
    
    - name: Send Slack Notification (Pi Down)
      if: steps.health-check.outputs.status == 'down' && secrets.SLACK_WEBHOOK
      run: |
        BACKUP_STATUS="${{ steps.health-check.outputs.backup-status }}"
        
        if [ "$BACKUP_STATUS" == "healthy" ]; then
          COLOR="warning"
          EMOJI=":warning:"
          STATUS_TEXT="Pi server down, backup healthy"
        else
          COLOR="danger"  
          EMOJI=":rotating_light:"
          STATUS_TEXT="CRITICAL: Both servers down"
        fi
        
        curl -X POST -H 'Content-type: application/json' \
          --data "{
            \"attachments\": [{
              \"color\": \"$COLOR\",
              \"title\": \"$EMOJI Third Voice API Health Alert\",
              \"text\": \"$STATUS_TEXT\",
              \"fields\": [
                {\"title\": \"Pi Server\", \"value\": \"❌ Unreachable\", \"short\": true},
                {\"title\": \"Backup\", \"value\": \"${{ steps.health-check.outputs.backup-status == 'healthy' && '✅ Healthy' || '❌ Down' }}\", \"short\": true},
                {\"title\": \"Time\", \"value\": \"$(date -u)\", \"short\": false}
              ]
            }]
          }" \
          ${{ secrets.SLACK_WEBHOOK }}
    
    - name: Log Successful Check
      if: steps.health-check.outputs.status == 'healthy'
      run: |
        echo "✅ Health check passed - Pi server responding normally"
        echo "✅ Backup server status: ${{ steps.health-check.outputs.backup-status }}"
