name: Keep Sip & Sing Backend Alive

on:
  schedule:
    # Run every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch: # Allow manual trigger from GitHub

jobs:
  ping-service:
    runs-on: ubuntu-latest

    steps:
    - name: Ping Sip & Sing Render Service
      run: |
        echo "$(date): Starting keep-alive ping for Sip & Sing..."
        
        # Root endpoint
        curl -f -s --max-time 10 --retry 3 --retry-delay 5 https://sip-n-sing-pwa.onrender.com/ \
          || echo "Root endpoint failed after retries"
        
        sleep 2
        
        # Health endpoint (adjust path if your API uses /api/health)
        curl -f -s --max-time 10 --retry 3 --retry-delay 5 https://sip-n-sing-pwa.onrender.com/api/health \
          || echo "Health endpoint failed after retries"
        
        echo "$(date): Keepalive ping completed successfully."
